name: Test and publish

on: [push]

jobs:
  test_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm test
    - uses: JS-DevTools/npm-publish@v1
      if: github.ref == 'refs/heads/main'
      with:
        token: ${{ secrets.NPM_TOKEN }}